modLoader="lowcodefml"
showAsResourcePack = false
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="gemlike"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
displayName="GemLike"
description='''
An Addon for Steven Universe Using Su_Gems and Gempire
'''

[[dependencies.gemlike]]
modId = "palladium"
mandatory = true
versionRange = "[4.4.1,)"
ordering = "NONE"
side = "BOTH"
